import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
} from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1
          className={clsx(
            "h-[var(--app-header-height)]",
            "p-3 bg-gray-600 font-bold text-white",
          )}
        >
          sync-raft
        </h1>

        {children}
      </body>
    </html>
  );
}
